FROM openjdk:17-jre-slim
VOLUME /tmp
COPY target/voiture-0.0.1-SNAPSHOT.jar myproject.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/myproject.jar"]


# docker build -t myproject .
# docker tag myproject registry.railway.app/ventevoitures5
# docker push registry.railway.app/ventevoitures5